
import Server.Server;
import Server.Message;
import Character.Player;
import Character.Bot;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.lang.System;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author komarov
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public static int countAttack;
    public static int countDefense;
    Server server;
    Player player;
    Bot bot;
    javax.swing.JCheckBox[] attackList;
    javax.swing.JCheckBox[] defenseList;
    String battleLog;
         
    public UI() {
        initComponents();
        Icon image1 = new ImageIcon("bot.jpeg");
        Icon image2 = new ImageIcon("player.jpeg");
        countAttack = 0;
        countDefense = 0;
        jLabel3.setIcon(image1);
        jLabel4.setIcon(image2);
        server = new Server();
        player = new Player();
        bot = new Bot();
        battleLog = new String();
        
        jLabel6.setText("HP: " + Integer.toString(player.maxHp) + "/" + Integer.toString(player.maxHp));
        jLabel7.setText("HP: " + Integer.toString(bot.maxHp) + "/" + Integer.toString(bot.maxHp));
        server.regPlayer(player);
        server.regBot(bot);
        
        attackList = new javax.swing.JCheckBox[6];
        defenseList = new javax.swing.JCheckBox[6];
        
        attackList[0] = headAttack;
        attackList[1] = bodyAttack;
        attackList[2] = rightHandAttack;
        attackList[3] = leftHandAttack;
        attackList[4] = rightLegAttack;
        attackList[5] = leftLegAttack;
        
        defenseList[0] = headDefense;
        defenseList[1] = bodyDefense;
        defenseList[2] = rightHandDefense;
        defenseList[3] = leftHandDefense;
        defenseList[4] = rightLegDefense;
        defenseList[5] = leftLegDefense;  
        
    }
    
    private void blockAttackCheck()
    {
        if (countAttack != 2)
        {
            for(int i = 0; i < 6; ++i)
            {
                attackList[i].setEnabled(true);
            }
        }
        else
        {
            for(int i = 0; i < 6; ++i)
            {
                if(!attackList[i].isSelected())
                    attackList[i].setEnabled(false);
            }
        }
    }
    private void blockDefenseCheck()
    {
        if (countDefense != 2)
        {
            for(int i = 0; i < 6; ++i)
            {
                defenseList[i].setEnabled(true);
            }
        }
        else
        {
            for(int i = 0; i < 6; ++i)
            {
                if(!defenseList[i].isSelected())
                    defenseList[i].setEnabled(false);
            }
        }
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        headAttack = new javax.swing.JCheckBox();
        bodyAttack = new javax.swing.JCheckBox();
        rightHandAttack = new javax.swing.JCheckBox();
        leftHandAttack = new javax.swing.JCheckBox();
        rightLegAttack = new javax.swing.JCheckBox();
        leftLegAttack = new javax.swing.JCheckBox();
        headDefense = new javax.swing.JCheckBox();
        bodyDefense = new javax.swing.JCheckBox();
        rightHandDefense = new javax.swing.JCheckBox();
        leftHandDefense = new javax.swing.JCheckBox();
        rightLegDefense = new javax.swing.JCheckBox();
        leftLegDefense = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logger = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("UI"));

        jButton1.setText("Make move");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        headAttack.setText("Голова");
        headAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headAttackActionPerformed(evt);
            }
        });

        bodyAttack.setText("Туловище");
        bodyAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyAttackActionPerformed(evt);
            }
        });

        rightHandAttack.setText("Правая рука");
        rightHandAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightHandAttackActionPerformed(evt);
            }
        });

        leftHandAttack.setText("Левая рука");
        leftHandAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftHandAttackActionPerformed(evt);
            }
        });

        rightLegAttack.setText("Правая нога");
        rightLegAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightLegAttackActionPerformed(evt);
            }
        });

        leftLegAttack.setText("Левая рука");
        leftLegAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftLegAttackActionPerformed(evt);
            }
        });

        headDefense.setText("Голова");
        headDefense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headDefenseActionPerformed(evt);
            }
        });

        bodyDefense.setText("Туловище");
        bodyDefense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyDefenseActionPerformed(evt);
            }
        });

        rightHandDefense.setText("Правая рука");
        rightHandDefense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightHandDefenseActionPerformed(evt);
            }
        });

        leftHandDefense.setText("Левая рука");
        leftHandDefense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftHandDefenseActionPerformed(evt);
            }
        });

        rightLegDefense.setText("Правая нога");
        rightLegDefense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightLegDefenseActionPerformed(evt);
            }
        });

        leftLegDefense.setText("Левая нога");
        leftLegDefense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftLegDefenseActionPerformed(evt);
            }
        });

        jLabel1.setText("Attack");

        jLabel2.setText("Defense");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rightLegAttack)
                            .addComponent(leftLegAttack)
                            .addComponent(leftHandAttack)
                            .addComponent(rightHandAttack))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leftHandDefense)
                            .addComponent(rightHandDefense)
                            .addComponent(rightLegDefense)
                            .addComponent(leftLegDefense)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(100, 100, 100))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(headAttack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bodyAttack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(42, 42, 42)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headDefense)
                            .addComponent(jLabel2)
                            .addComponent(bodyDefense)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headAttack)
                    .addComponent(headDefense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodyAttack)
                    .addComponent(bodyDefense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightHandAttack)
                    .addComponent(rightHandDefense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftHandAttack)
                    .addComponent(leftHandDefense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightLegAttack)
                    .addComponent(rightLegDefense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftLegAttack)
                    .addComponent(leftLegDefense))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(13, 13, 13))
        );

        jButton2.setText("exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("bot");

        jLabel4.setText("player");

        logger.setColumns(40);
        logger.setRows(5);
        jScrollPane1.setViewportView(logger);

        jLabel5.setText("Battle Log:");

        jLabel6.setText("HP:");

        jLabel7.setText("HP:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(73, 73, 73)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(101, 101, 101))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel3.getAccessibleContext().setAccessibleName(" ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed


    //Защита левой ноги
    private void leftLegDefenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftLegDefenseActionPerformed
        if (leftLegDefense.isSelected())
            ++countDefense;
        else
            --countDefense;

       blockDefenseCheck();
    }//GEN-LAST:event_leftLegDefenseActionPerformed
    //Защита правой ноги
    private void rightLegDefenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightLegDefenseActionPerformed

        if (rightLegDefense.isSelected())
            ++countDefense;
        else
            --countDefense;

        blockDefenseCheck();
    }//GEN-LAST:event_rightLegDefenseActionPerformed
    //Защита левой руки
    private void leftHandDefenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftHandDefenseActionPerformed
        if (leftHandDefense.isSelected())
            ++countDefense;
        else
            --countDefense;

        blockDefenseCheck();
    }//GEN-LAST:event_leftHandDefenseActionPerformed
    //Защита правой руки
    private void rightHandDefenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightHandDefenseActionPerformed
        if (rightHandDefense.isSelected())
            ++countDefense;
        else
            --countDefense;

        blockDefenseCheck();
    }//GEN-LAST:event_rightHandDefenseActionPerformed
    //Защита туловища
    private void bodyDefenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyDefenseActionPerformed
        if (bodyDefense.isSelected())
            ++countDefense;
        else
            --countDefense;

        blockDefenseCheck();
    }//GEN-LAST:event_bodyDefenseActionPerformed
    //Защита головы
    private void headDefenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headDefenseActionPerformed
        if (headDefense.isSelected())
            ++countDefense;
        else
            --countDefense;

        blockDefenseCheck();
    }//GEN-LAST:event_headDefenseActionPerformed
    //Атака левой ноги
    private void leftLegAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftLegAttackActionPerformed
        if (leftLegAttack.isSelected())
            ++countAttack;
        else
            --countAttack;

        blockAttackCheck();
    }//GEN-LAST:event_leftLegAttackActionPerformed
    //Атака правой ноги
    private void rightLegAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightLegAttackActionPerformed
        if (rightLegAttack.isSelected())
            ++countAttack;
        else
            --countAttack;

        blockAttackCheck();
    }//GEN-LAST:event_rightLegAttackActionPerformed
    //Атака левой руки
    private void leftHandAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftHandAttackActionPerformed
        if (leftHandAttack.isSelected())
            ++countAttack;
        else
            --countAttack;

        blockAttackCheck();
    }//GEN-LAST:event_leftHandAttackActionPerformed
    //Атака правой руки
    private void rightHandAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightHandAttackActionPerformed

        if (rightHandAttack.isSelected())
            ++countAttack;
        else
            --countAttack;

        blockAttackCheck();
    }//GEN-LAST:event_rightHandAttackActionPerformed
    //Атака туловища
    private void bodyAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyAttackActionPerformed
        if (bodyAttack.isSelected())
            ++countAttack;
        else
            --countAttack;

        blockAttackCheck();
    }//GEN-LAST:event_bodyAttackActionPerformed
    //Атака головы
    private void headAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headAttackActionPerformed
        if (headAttack.isSelected())
            ++countAttack;
        else
            --countAttack;

        blockAttackCheck();
    }//GEN-LAST:event_headAttackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            boolean[] attack = new boolean[6];
            boolean[] defense = new boolean[6];
            
            for (int i = 0; i < 6; ++i)
            {
                attack[i] = attackList[i].isSelected();
                defense[i] = defenseList[i].isSelected();
            }
        
            
            battleLog += server.translateMessage(new Message(attack, defense, bot.choiceAttack(), bot.choiceDefense())) + "\n";
            
            
            jLabel6.setText("HP: " + Integer.toString(player.currentHp) + "/" + Integer.toString(player.maxHp));
            jLabel7.setText("HP: " + Integer.toString(bot.currentHp) + "/" + Integer.toString(bot.maxHp));
            
            if (player.currentHp <= 0)
            {
                battleLog += "Бой окончен! Игрок проиграл.\nТак же вы потратили " +  Long.toString(System.currentTimeMillis()) 
                          + " миллисекунд своей жизни.\n";
                player.currentHp = player.maxHp;
                bot.currentHp = bot.maxHp;
            }
            else if (bot.currentHp <= 0)
            {
                battleLog += "Бой окончен! Бот проиграл.\n"+  Long.toString(System.currentTimeMillis()) 
                          + " миллисекунд своей жизни.\n"; 
                player.currentHp = player.maxHp;
                bot.currentHp = bot.maxHp;
            }
            if (player.currentHp <= 0 && bot.currentHp <= 0)
            {
                battleLog += "Бой окончен! Ничья.\n" +  Long.toString(System.currentTimeMillis()) 
                          + " миллисекунд своей жизни.\n";
                player.currentHp = player.maxHp;
                bot.currentHp = bot.maxHp;
            }
            logger.setText(battleLog);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bodyAttack;
    private javax.swing.JCheckBox bodyDefense;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox headAttack;
    private javax.swing.JCheckBox headDefense;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox leftHandAttack;
    private javax.swing.JCheckBox leftHandDefense;
    private javax.swing.JCheckBox leftLegAttack;
    private javax.swing.JCheckBox leftLegDefense;
    private javax.swing.JTextArea logger;
    private javax.swing.JCheckBox rightHandAttack;
    private javax.swing.JCheckBox rightHandDefense;
    private javax.swing.JCheckBox rightLegAttack;
    private javax.swing.JCheckBox rightLegDefense;
    // End of variables declaration//GEN-END:variables
}
